encoding: utf-8
name: Mayank Lunayach
url: mayank.lunayach.me
author:
  name: Mayank Lunayach
  email: mayanklunayach@gmail.com
description: CS Graduate student at Georgia Tech
permalink: /posts/:title/
include: ['_pages']
